services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0.3-ubuntu2204
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: user
      MONGODB_INITDB_ROOT_PASSWORD: password
